title: "Contract-First IDP"
author: "Contract-First IDP Team"
description: "An OpenShift developer platform reference architecture for contract-first application delivery."
github_username: "contract-first-idp"

theme: "minima"
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      layout: post
      author: David Gordon
      github_username: davgordo
      tags: Architecture
